---

homebrew_installed_packages: []
  # - ansible # Installed via Pip.
  # - autoconf
  # - bash-completion
  # - httpie
  # - sqlite
  # - ssh-copy-id
  # - readline
  # - openssl
  # - wget

homebrew_uninstalled_packages: []

homebrew_taps: []
  # - homebrew/core
  # - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps: []
  # - chromedriver
  # - docker
  # - firefox
  # - google-chrome
  # - handbrake
  # - licecap
  # - limechat
  # - sequel-pro
  # - sublime-text
  # - transmit
  # - vagrant

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []

# Install packages from other package managers.
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A
