---
- name: mac setup 
  hosts: localhost
  connection: local
  
  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: common
      tags: ['common']
    - role: brew
      tags: ['brew']
    - role: pip
      tags: ['pip']
      

    



















